server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springdeveloper123/spring-cloud-config-server-db
          search-paths:
          - app*
          force-pull: true
          repos:
            jndi:
              pattern:
              - "*/jndi"
              uri: https://github.com/springdeveloper123/spring-cloud-config-server-db-jndi
              search-paths:
               - app*